### ISSUE TITLE
WARNING: Error parsing requirements for cord19

### ISSUE THREAD

**Issue by crameth** [dgunning/cord19#1]
getting this error:

`WARNING: Error parsing requirements for cord19: Parse error at "'(===1.4.'": Expected stringEnd`

after doing `pip install git+https://github.com/dgunning/cord19.git`

consequently, seems like some of the required modules were not being installed, such as annoy.

**Comment by dgunning** [comment]
I think annoy was left off requirements.txt by mistake. I added it.

Still trying to fix that pip exception though, which is annoying.

Can you retry with -U?

pip install -U git+https://github.com/dgunning/cord19.git

**Comment by dgunning** [comment]
Fixed and pushed
