### ISSUE TITLE
retrieving relevant documents using precision at k = #

### ISSUE THREAD

**Issue by abdallahnazmy** [dgunning/cord19#3]
I was wondering , how would i go about prioritizing the output documents according to precision at k = 3 for example , this is for a uni project and i need to sort the output papers according to their relevance ?

**Comment by dgunning** [comment]
The results of search are sorted by the relevance scores so the output documents are already in sorted order. But what do you mean by precision - is there some other order to sort by?

**Comment by dgunning** [comment]
Closed
